insert into TODO_ITEM (ID, USERNAME, DESCRIPTION, DUE_DATE, IS_DONE)
values (10001, 'vxbxv7', 'Get Groceries', CURRENT_DATE, false);

INSERT INTO TODO_ITEM (ID, USERNAME, DESCRIPTION, DUE_DATE, IS_DONE)
VALUES (10002, 'vxbxv7', 'Complete Assignment', CURRENT_DATE + 1, false);

INSERT INTO TODO_ITEM (ID, USERNAME, DESCRIPTION, DUE_DATE, IS_DONE)
VALUES (10003, 'alice', 'Call the Plumber', CURRENT_DATE + 2, true);

INSERT INTO TODO_ITEM (ID, USERNAME, DESCRIPTION, DUE_DATE, IS_DONE)
VALUES (10004, 'vxbxv7', 'Read Book Chapter 5', CURRENT_DATE + 3, false);

INSERT INTO TODO_ITEM (ID, USERNAME, DESCRIPTION, DUE_DATE, IS_DONE)
VALUES (10005, 'alice', 'Pay Electricity Bill', CURRENT_DATE + 4, false);

INSERT INTO TODO_ITEM (ID, USERNAME, DESCRIPTION, DUE_DATE, IS_DONE)
VALUES (10006, 'vxbxv7', 'Prepare Presentation', CURRENT_DATE + 5, true);

INSERT INTO TODO_ITEM (ID, USERNAME, DESCRIPTION, DUE_DATE, IS_DONE)
VALUES (10007, 'alice', 'Workout Session', CURRENT_DATE + 6, false);

INSERT INTO TODO_ITEM (ID, USERNAME, DESCRIPTION, DUE_DATE, IS_DONE)
VALUES (10008, 'vxbxv7', 'Buy Birthday Gift', CURRENT_DATE + 7, false);

INSERT INTO TODO_ITEM (ID, USERNAME, DESCRIPTION, DUE_DATE, IS_DONE)
VALUES (10009, 'alice', 'Attend Meeting', CURRENT_DATE + 8, true);

INSERT INTO TODO_ITEM (ID, USERNAME, DESCRIPTION, DUE_DATE, IS_DONE)
VALUES (10010, 'vxbxv7', 'Schedule Doctor Appointment', CURRENT_DATE + 9, false);

INSERT INTO TODO_ITEM (ID, USERNAME, DESCRIPTION, DUE_DATE, IS_DONE)
VALUES (10011, 'alice', 'Plan Weekend Trip', CURRENT_DATE + 10, false);
